env:
  browser: true
extends:
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - react-hooks
  - react
rules:
  react/no-unescaped-entities: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
